version: '3.5'

services:

  php-service:
    build:
      dockerfile: docker/php/Dockerfile
    container_name: wallet-php-${DOCKER_COMPOSE_ENV}
    volumes:
      - ./:/var/www
#      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
      - ./docker/php/conf.d/zzz_memory_limit.ini:/usr/local/etc/php/conf.d/zzz_memory_limit.ini
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-net

  nginx-service:
    image: nginx:1.25-alpine
    container_name: wallet-nginx-${DOCKER_COMPOSE_ENV}
    restart: always
    ports:
      - "${NGPORTS}"
    volumes:
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./:/var/www
    networks:
      - app-net

  postgres-service:
    image: postgres:15-alpine
    container_name: wallet-postgres-${DOCKER_COMPOSE_ENV}
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORTS}"
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
      - ./docker/postgres/tmp:/tmp:wr
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
