version: '3.5'

services:

  php-service:
    image: php-image
    build:
      dockerfile: docker/php/Dockerfile
    container_name: php-container
    volumes:
      - ./:/var/www
    networks:
      - app-net

  nginx-service:
    image: nginx:1.25-alpine
    container_name: nginx-container
    restart: always
    ports:
      - "${NGPORTS}"
    volumes:
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./:/var/www
    networks:
      - app-net

  postgres-service:
    image: postgres:14.5-alpine
    container_name: postgres-container
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORTS}"
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
      - ./docker/postgres/tmp:/tmp:wr
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

