parameters:
    app.supported_locales: 'pl|en'
services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler:
        arguments:
            - '%env(DATABASE_URL)%'

    App\Service\BalanceUpdater\BalanceUpdaterBackup: ~
    App\Service\BalanceUpdater\BalanceUpdaterAccountInterface $backup: '@App\Service\BalanceUpdater\BalanceUpdaterBackup'

    App\Service\BalanceUpdater\BalanceUpdaterWallet: ~
    App\Service\BalanceUpdater\BalanceUpdaterAccountInterface $wallet: '@App\Service\BalanceUpdater\BalanceUpdaterWallet'

    App\Service\BalanceUpdater\BalanceUpdaterBackupFactory: ~
    App\Service\BalanceUpdater\BalanceUpdaterFactoryInterface $backupFactory: '@App\Service\BalanceUpdater\BalanceUpdaterBackupFactory'

    App\Service\BalanceUpdater\BalanceUpdaterWalletFactory: ~
    App\Service\BalanceUpdater\BalanceUpdaterFactoryInterface $walletFactory: '@App\Service\BalanceUpdater\BalanceUpdaterWalletFactory'

    App\Repository\ChfRepository: ~
    App\Repository\AccountRepositoryInterface $chfRepository: '@App\Repository\ChfRepository'

    App\Repository\EurRepository: ~
    App\Repository\AccountRepositoryInterface $eurRepository: '@App\Repository\EurRepository'

    App\Repository\FeeRepository: ~
    App\Repository\FeeRepositoryInterface $feeRepository: '@App\Repository\FeeRepository'

    App\Service\RequestParser\SearchHelper: ~
    App\Service\RequestParser\ControllerHelperInterface $searchHelper: '@App\Service\RequestParser\SearchHelper'

    App\Service\RequestParser\WalletHelper: ~
    App\Service\RequestParser\ControllerHelperInterface $walletHelper: '@App\Service\RequestParser\WalletHelper'

    App\State\WalletProcessor:
        bind:
            $persistProcessor: '@api_platform.doctrine.orm.state.persist_processor'
            $removeProcessor: '@api_platform.doctrine.orm.state.remove_processor'

    App\State\BackupProcessor:
        bind:
            $persistProcessor: '@api_platform.doctrine.orm.state.persist_processor'
            $removeProcessor: '@api_platform.doctrine.orm.state.remove_processor'

    App\State\ChfProcessor:
        bind:
            $persistProcessor: '@api_platform.doctrine.orm.state.persist_processor'
            $removeProcessor: '@api_platform.doctrine.orm.state.remove_processor'

    App\OpenApi\JwtDecorator:
        decorates: 'api_platform.openapi.factory'
        arguments: [ '@.inner' ]
