parameters:
    app.supported_locales: 'pl|en'
services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler:
        arguments:
            - '%env(DATABASE_URL)%'

    App\Service\BalanceUpdater\BackupBalanceUpdater: ~
    App\Service\BalanceUpdater\BalanceUpdaterInterface $backupUpdater: '@App\Service\BalanceUpdater\BackupBalanceUpdater'

    App\Service\BalanceUpdater\WalletBalanceUpdater: ~
    App\Service\BalanceUpdater\BalanceUpdaterInterface: '@App\Service\BalanceUpdater\WalletBalanceUpdater'

    App\Service\RequestParser\Search: ~
    App\Service\RequestParser\ControllerInterface $search: '@App\Service\RequestParser\Search'

    App\Service\RequestParser\Wallet: ~
    App\Service\RequestParser\ControllerInterface: '@App\Service\RequestParser\Wallet'
