parameters:
    app.supported_locales: 'pl|en'
services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler:
        arguments:
            - '%env(DATABASE_URL)%'

    App\Service\BalanceUpdater\BackupBalanceUpdater: ~
    App\Service\BalanceUpdater\BalanceUpdaterInterface $backupUpdater: '@App\Service\BalanceUpdater\BackupBalanceUpdater'

    App\Service\BalanceUpdater\WalletBalanceUpdater: ~
    App\Service\BalanceUpdater\BalanceUpdaterInterface: '@App\Service\BalanceUpdater\WalletBalanceUpdater'

    App\Repository\ChfRepository: ~
    App\Repository\AccountRepositoryInterface $chf: '@App\Repository\ChfRepository'

    App\Repository\EurRepository: ~
    App\Repository\AccountRepositoryInterface $eur: '@App\Repository\EurRepository'

    App\Repository\FeeRepository: ~
    App\Repository\FeeRepositoryInterface $fee: '@App\Repository\FeeRepository'

    App\Service\RequestParser\Search: ~
    App\Service\RequestParser\ControllerInterface $search: '@App\Service\RequestParser\Search'

    App\Service\RequestParser\Wallet: ~
    App\Service\RequestParser\ControllerInterface: '@App\Service\RequestParser\Wallet'

    App\EntityListener\BackupEntityListener:
        tags:
            - { name: 'doctrine.orm.entity_listener', event: 'prePersist', entity: 'App\Entity\Backup' }
            - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', entity: 'App\Entity\Backup' }
